import { ALL_PERMISSION_KEYS } from "@/lib/permissionRegistry";

// Permission mac dinh cho 6 vai tro he thong, suy ra tu cac requireRole(...) /
// role-array constant thuc te trong code truoc khi co permission dong (khong
// dung nguyen vi du minh hoa cua spec) de dam bao hanh vi giu nguyen nhu truoc.
// Dung chung boi scripts/seed.ts (seed du lieu thuc) va tests/helpers.ts (seed
// Role cho test) de tranh hai noi bi lech nhau.
export const SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> = {
    admin: ALL_PERMISSION_KEYS,
    neighborhood_leader: [
        "dashboard.read",
        "houses.read",
        "houses.verify",
        "households.read",
        "citizens.read",
        "business_types.read",
        "businesses.read",
        "complaints.read",
        "complaints.assign",
        "complaints.update_status",
        "pccc.read",
        "security.read",
        "meetings.read",
        "meetings.register",
        "announcements.read",
        "surveys.read",
        "surveys.respond",
        "reports.read",
        "reports.export",
        "exports.export",
        "support_tickets.create",
        "support_tickets.read_own",
        "files.read",
        "notifications.read",
    ],
    secretary: [
        "dashboard.read",
        "houses.read",
        "houses.verify",
        "households.read",
        "citizens.read",
        "business_types.read",
        "businesses.read",
        "meetings.read",
        "meetings.create",
        "meetings.update",
        "meetings.publish",
        "meetings.register",
        "announcements.read",
        "announcements.create",
        "announcements.update",
        "announcements.publish",
        "surveys.read",
        "surveys.create",
        "surveys.update",
        "surveys.publish",
        "surveys.respond",
        "support_tickets.create",
        "support_tickets.read_own",
        "files.read",
        "files.create",
        "files.update",
        "files.delete",
        "notifications.read",
    ],
    regional_police: [
        "dashboard.read",
        "houses.read",
        "households.read",
        "citizens.read",
        "business_types.read",
        "businesses.read",
        "complaints.read",
        "complaints.assign",
        "complaints.update_status",
        "pccc.read",
        "pccc.create",
        "pccc.update",
        "security.read",
        "security.create",
        "security.update",
        "reports.read",
        "reports.export",
        "meetings.register",
        "surveys.respond",
        "support_tickets.create",
        "support_tickets.read_own",
        "files.read",
        "notifications.read",
    ],
    people_committee_official: [
        "dashboard.read",
        "houses.read",
        "houses.verify",
        "households.read",
        "citizens.read",
        "business_types.read",
        "businesses.read",
        "complaints.read",
        "complaints.assign",
        "complaints.update_status",
        "pccc.read",
        "security.read",
        "meetings.register",
        "surveys.respond",
        "support_tickets.create",
        "support_tickets.read_own",
        "files.read",
        "notifications.read",
    ],
    resident: [
        "houses.read",
        "houses.create",
        "houses.update",
        "households.read",
        "households.create",
        "households.update",
        "citizens.read",
        "citizens.create",
        "citizens.update",
        "citizens.delete",
        "complaints.create",
        "complaints.read_own",
        "support_tickets.create",
        "support_tickets.read_own",
        "meetings.register",
        "surveys.respond",
        "files.read",
        "notifications.read",
    ],
};
